### ISSUE TITLE
Matching version of clj-kondo

### ISSUE THREAD

**Issue by rome-user** [clj-kondo/lein-clj-kondo#13]
Do you think it would make sense to match the version of clj-kondo so that users can easily determine the version of clj-kondo in use? At the moment, the only way to find out is by viewing information on Clojars or the project.clj file.

The downside I see is that changes to the plugin itself are no longer encoded with semver. I want to hear feedback on this.

**Comment by borkdude** [comment]
Sounds like an idea to me.

**Comment by ericdallo** [comment]
I like it, it's actually how [lein-clojure-lsp](https://github.com/clojure-lsp/lein-clojure-lsp) works, but for that works there is an automation every clojure-lsp release to automatically bump and release lein-clojure-lsp as well

**Comment by borkdude** [comment]
done
